### ISSUE TITLE
Documentation Evaluation and Update

### ISSUE THREAD

**Issue by BCerki** [thebuttonclan/pangolin#476]
### Description
As a developer
I want the documentation to be clear
So that I understand how to use the component library and form builder, and how to develop or contribute to the repo

Right now there are instructions in Storybook and several readmes, and some of the information is duplicated. It's hard to find the information you need and the duplication is a risk for conflicting information

### Tasks (How)

- [ ] Add a Getting Started section to the Button Storybook. Check out [Storybook Composition](https://medium.com/storybookjs/storybook-composition-af0da9084fba) to see if we can avoid copy/pasting from bcgov
- [ ] Move the Theming section from the BCGov Storybook to the Button one
- [ ] Update/remove any old information
- [ ] use a different component than `Button` in the installation instructions (confusing cause component, package, and company all called button)
- [ ] Consider reorganizing the main github README into the following sections (use whatever heading names you like):
- Using the Tools
- - Toolkit
- - Form Builder
- Developing/Contributing
- - subsections as needed
- - link to dev guide
- [ ] Evaluate whether all the other READMEs are necessary or could be rolled into Storybook or the main README (or deleted if they're duplicated)

Notes:
- `components.md` is generated and only applies to the Button components

~~There are three (unconfirmed) audiences for the documentation:~~
~~1. Developers who want to contribute to the repo (Innovation team, and also maybe developers who use the components and want to make improvements)~~
~~2. Developers who want to use the BCGov components (BCGov developers and Button developers on BCGov teams), the Button components (community?), or the form builder (community?)~~
~~3. Developers who want to make their own theme (community?)~~

~~Right now there are instructions in Storybook and several readmes, and some of the information is duplicated. It's hard to find the information you need and the duplication is a risk for conflicting information~~

~~### Tasks (How)~~

~~- [ ] Add a Getting Started section to the Button Storybook using the BCGov section as a template, and move/copy any readme documentation related to audience 2 or 3 to there~~
~~- [ ] Move/copy any readme documentation related to audience 2 into the Getting Started section of the BCGov Storybook~~
~~- [ ] Move the Theming section from the BCGov Storybook to the Button one~~
~~- [ ] Reoganize the main README into the following sections (use whatever heading names you like):~~
~~- Using the Tools (audience 2)~~
~~- - Toolkit~~
~~- - Form Builder~~
~~- Developing/Contributing (audience 1 and 3)~~
~~- - subsections as needed~~
~~- [ ] Evaluate whether all the other READMEs are necessary or could be rolled into the main README (or deleted if they're duplicated)~~

**Comment by BCerki** [comment]
I'm not sure if it's better to have "Using the Toolkit" instructions in both the README and Storybook, or to just link to Storybook from the README. Duplicating it means having to keep it updated in two places, but someone arriving at the repo vs. Storybook might prefer to have it right in front of them rather than following a link.

Looking at Material UI, they link to their website (equivalent of Storybook) from the readme but do include installation instructions and an example directly in the readme.
