### ISSUE TITLE
Add Navigation component to Button theme

### ISSUE THREAD

**Issue by BCerki** [thebuttonclan/pangolin#500]
### Description
As a Toolkit user
I want the Button theme to offer a Navigation component
So that I can use the Navigation component in my project (reusable, time-saver, progressive enhancement)
### Tasks (How)
- [ ] make a [componentName].tsx file in packages/[theme/src/ (can copy/paste the one that already exists in the bcgov theme but remove any bcgov-specific imagery or text)
- [ ] make the component use the global styles object (see Button alert for an example)
- [ ] make a [componentName].stories.tsx file in packages/[theme]/stories (again can copy/paste, note that the gov theme has extra stuff and a different file structure we don't need in the Button theme (this is an assumption but if it's wrong we can address it later in tech debt))
- [ ] update the stories file if necessary to apply to the Button theme
- [ ] jest tests

**Comment by BCerki** [comment]
Closing because the Button header already includes navigation
