### ISSUE TITLE
Add Notification component to bcgov theme

### ISSUE THREAD

**Issue by BCerki** [thebuttonclan/pangolin#501]
SEE CHECK STATUS OF #509 BEFORE DOING THIS TICKET
### Description
As a Toolkit user
I want the Button theme to offer a Navigation component
So that I can use the Navigation component in my project (reusable, time-saver, progressive enhancement)
### Tasks (How)
- [ ] make a [componentName].tsx file in packages/[theme/src/ (can probably copy/paste the one that already exists in the button theme)
- [ ] update the component files styles to match the wireframes
- [ ] make a [componentName] file in packages/[theme]/stories (see the other components' files for an example). We'll need copy but I think the rest of the material can be based off of what's in other components.

**Comment by BCerki** [comment]
Addressing in #509 instead
