### ISSUE TITLE
Investigate adding CCBC components to Toolkit

### ISSUE THREAD

**Issue by BCerki** [thebuttonclan/pangolin#534]
### Description
The CCBC team created some bcgov-themed components that we might be able to add to the Toolkit. This ticket is about investigating what's already been done and deciding if we want to bring the components into Toolkit.

As a developer and designer
I want to resuse components created in other projects
So that I can speed up my work
### Tasks (How)
- [ ] Ask Zoey and Marcel to point you toward the CCBC components
- [ ] Determine if the components already incorporate progressive enhancement
- [ ] Determine if the components will need base components in the `component-library`
