### ISSUE TITLE
Create bcgov Filepicker component

### ISSUE THREAD

**Issue by BCerki** [thebuttonclan/pangolin#557]
### Description
As a Toolkit user
I want the bcgov theme to offer an Filepicker component
So that I can use the Filepicker component in my project (reusable, time-saver, progressive enhancement)
### Tasks (How)
- [ ] check with Connectivity team about designs
- [ ] make a [componentName].tsx file in packages/[theme/src/ (can copy/paste the one that already exists in the button theme)
- [ ] create a stories folder for the component (see other bcgov component stories for an example)
- [ ] jest tests

**Comment by BCerki** [comment]
Both themes have this component
