### ISSUE TITLE
Create Button Typography component

### ISSUE THREAD

**Issue by BCerki** [thebuttonclan/pangolin#558]
### Description
As a Toolkit user
I want the Button theme to offer an Typography component
So that I can use the Typography component in my project (reusable, time-saver, progressive enhancement)
### Tasks (How)
- [ ] investigate the existing Button `Typography` component (it's not showing up in Storybook so it may not be fully completed)
- [ ] make a [componentName].stories.tsx file in packages/[theme]/stories (again can copy/paste, note that the gov theme has extra stuff and a different file structure we don't need in the Button theme (this is an assumption but if it's wrong we can address it later in tech debt))
- [ ] update the stories file if necessary to apply to the Button theme
- [ ] jest tests
