### ISSUE TITLE
Move to open source happo account

### ISSUE THREAD

**Issue by BCerki** [thebuttonclan/pangolin#578]
### Description
As a toolkit contributor
I want to use the happo open source plan
So that I can have continued access to happo
### Tasks (How)
- [x] Determine if Button already has a happo account
- [ ] If yes, update the repo secrets to use the Button account
- [ ] If not, talk to happo about setting up an open-source account: https://happo.io/pricing#:~:text=Can%20I%20use,get%20things%20started.
